// src/social-share-button-preact.jsx
import { useEffect, useRef } from "preact/hooks";

/**
 * A Preact wrapper around the vanilla SocialShareButton library.
 * Initializes the widget on mount, syncs prop changes via updateOptions,
 * and destroys the instance on unmount.
 *
 * @param {string} url - URL to share (defaults to current page)
 * @param {string} title - Share title (defaults to document.title)
 * @param {string} description - Share description
 * @param {string[]} hashtags - Hashtags for supported platforms
 * @param {string} via - Twitter via handle
 * @param {string[]} platforms - Platforms to display
 * @param {string} theme - 'dark' | 'light'
 * @param {string} buttonText - Label on the share button
 * @param {string} customClass - Extra CSS class on the container
 * @param {Function|null} onShare - Callback fired on share
 * @param {Function|null} onCopy - Callback fired on link copy
 * @param {string} buttonStyle - Button style variant
 * @param {string} modalPosition - 'center' | 'top' | 'bottom'
 */
export default function SocialShareButton({
  url = "",
  title = "",
  description = "",
  hashtags = [],
  via = "",
  platforms = [
    "whatsapp",
    "facebook",
    "twitter",
    "linkedin",
    "telegram",
    "reddit",
  ],
  theme = "dark",
  buttonText = "Share",
  customClass = "",
  onShare = null,
  onCopy = null,
  buttonStyle = "default",
  modalPosition = "center",
}) {
  const containerRef = useRef(null);
  const shareButtonRef = useRef(null);

  useEffect(() => {
    let checkInterval = null;

    const initButton = () => {
       if (shareButtonRef.current) return;
      if (containerRef.current) {
        shareButtonRef.current = new window.SocialShareButton({
          container: containerRef.current,
          url: url || window.location.href,
          title: title || document.title,
          description,
          hashtags,
          via,
          platforms,
          theme,
          buttonText,
          customClass,
          onShare,
          onCopy,
          buttonStyle,
          modalPosition,
        });
      }
    };

    if (typeof window === "undefined") return () => {};

    if (window.SocialShareButton) {
      initButton();
    } else {
      checkInterval = setInterval(() => {
        if (window.SocialShareButton) {
          clearInterval(checkInterval);
          checkInterval = null;
          initButton();
        }
      }, 100);
    }
    return () => {
      if (checkInterval) clearInterval(checkInterval);
      if (shareButtonRef.current) {
        shareButtonRef.current.destroy();
        shareButtonRef.current = null;
      }
    };
  }, []);

// Serialize arrays to detect actual value changes vs. new array references
  const hashtagsDep = JSON.stringify(hashtags);
  const platformsDep = JSON.stringify(platforms);

  useEffect(() => {
    if (shareButtonRef.current) {
      shareButtonRef.current.updateOptions({
        url,
        title,
        description,
        hashtags,
        via,
        platforms,
        theme,
        buttonText,
        customClass,
        onShare,
        onCopy,
        buttonStyle,
        modalPosition,
      });
    }
  }, [
    url,
    title,
    description,
    hashtagsDep,
    via,
    platformsDep,
    theme,
    buttonText,
    customClass,
    onShare,
    onCopy,
    buttonStyle,
    modalPosition,
  ]);

  return <div ref={containerRef}></div>;
}

// src/social-share-button-qwik.tsx
import { component$, useVisibleTask$, useSignal, type QRL } from '@builder.io/qwik';

interface Props {
  url?: string;
  title?: string;
  description?: string;
  hashtags?: string[];
  via?: string;
  platforms?: string[];
  theme?: 'dark' | 'light';
  buttonText?: string;
  customClass?: string;
  buttonStyle?: 'default' | 'primary' | 'compact' | 'icon-only';
  modalPosition?: 'center' | 'top' | 'bottom';
  onShare?: QRL<(platform: string, url: string) => void>;
  onCopy?: QRL<(url: string) => void>;
}

export const SocialShareButton = component$<Props>((props) => {
  const containerRef = useSignal<HTMLDivElement>();

  
  useVisibleTask$(({ cleanup }) => {
    if (typeof window !== 'undefined' && (window as any).SocialShareButton && containerRef.value) {
      const shareButton = new (window as any).SocialShareButton({
        container: containerRef.value,
        url: props.url || window.location.href,
        title: props.title || document.title,
        description: props.description || '',
        hashtags: props.hashtags || [],
        via: props.via || '',
        platforms: props.platforms || ['whatsapp', 'facebook', 'twitter', 'linkedin', 'telegram', 'reddit'],
        theme: props.theme || 'dark',
        buttonText: props.buttonText || 'Share',
        customClass: props.customClass || '',
        buttonStyle: props.buttonStyle || 'default',
        modalPosition: props.modalPosition || 'center',
        onShare: props.onShare,
        onCopy: props.onCopy,
      });


      cleanup(() => {
        if (shareButton && typeof shareButton.destroy === 'function') {
          shareButton.destroy();
        }
      });
    }
  });

  return <div ref={containerRef} class="qwik-social-share-wrapper"></div>;
});
